"""add name_es to exercises

Revision ID: 18f6538e7047
Revises: b1629210716a
Create Date: 2026-07-21 02:15:59.270028

"""
from alembic import op
import sqlalchemy as sa


revision = '18f6538e7047'
down_revision = 'b1629210716a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('name_es', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'name_es')
    # ### end Alembic commands ###