"""add archived to exercises

Revision ID: 80861d965c3c
Revises: 18f6538e7047
Create Date: 2026-07-28 14:50:32.560906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '80861d965c3c'
down_revision = '18f6538e7047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('archived', sa.Integer(), nullable=True))
    op.drop_column('exercises', 'name_es')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('name_es', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('exercises', 'archived')
    # ### end Alembic commands ###